package com.vesmax.model;
// Generated Aug 4, 2019 6:35:03 PM by Hibernate Tools 5.1.7.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name = "images", schema = "dbo", catalog = "Qlspa")
public class Images  {

	private Integer id;
	private String photo;
	private String title;
	private String content;
	private String description;
	private Integer image_type;

	public Images() {
	}

	

	public Images(String photo, String title, String content, String description, Integer image_type) {
		super();
		this.photo = photo;
		this.title = title;
		this.content = content;
		this.description = description;
		this.image_type = image_type;
	}
	
	


	public Integer getImage_type() {
		return image_type;
	}



	public void setImage_type(Integer image_type) {
		this.image_type = image_type;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Photo")
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

}
