package com.vesmax.model;
// Generated Aug 3, 2019 10:57:36 AM by Hibernate Tools 5.1.7.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", schema = "dbo", catalog = "Qlspa")
public class Orders {

	private Integer id;
	private Services services;
	private Users users;
	private Integer number;
	private String date;
	private String minute;
	private String seconds;
	private String location;
	private String round;
	private Integer orderStatus;

	public Orders(Services services, Users users, Integer number, String date, String minute, String seconds,
			Integer orderStatus) {
		super();
		this.services = services;
		this.users = users;
		this.number = number;
		this.date = date;
		this.minute = minute;
		this.seconds = seconds;
		this.orderStatus = orderStatus;
	}
	

	public Orders(Services services, Users users, Integer number, String date, String minute, String seconds,
			String location, String round, Integer orderStatus) {
		super();
		this.services = services;
		this.users = users;
		this.number = number;
		this.date = date;
		this.minute = minute;
		this.seconds = seconds;
		this.location = location;
		this.round = round;
		this.orderStatus = orderStatus;
	}
	

	@JoinColumn(name = "location")
	public String getLocation() {
		return location;
	}


	public void setLocation(String location) {
		this.location = location;
	}

	@JoinColumn(name = "location")
	public String getRound() {
		return round;
	}


	public void setRound(String round) {
		this.round = round;
	}


	@JoinColumn(name = "minute")
	public String getMinute() {
		return minute;
	}

	@JoinColumn(name = "date")
	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public void setMinute(String minute) {
		this.minute = minute;
	}

	@JoinColumn(name = "seconds")
	public String getSeconds() {
		return seconds;
	}

	public void setSeconds(String seconds) {
		this.seconds = seconds;
	}

	private Set<StaffsOrder> staffsOrders = new HashSet<StaffsOrder>(0);

	public Orders() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "services_Id")
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_Id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Column(name = "order_status")
	public Integer getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<StaffsOrder> getStaffsOrders() {
		return this.staffsOrders;
	}

	public void setStaffsOrders(Set<StaffsOrder> staffsOrders) {
		this.staffsOrders = staffsOrders;
	}

}
