package com.vesmax.model;
// Generated Aug 4, 2019 6:35:03 PM by Hibernate Tools 5.1.7.Final


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name = "services", schema = "dbo", catalog = "Qlspa")
public class Services {

	private Integer id;
	private String name;
	private Float price;
	private String images;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Services() {
	}

	public Services(String name, Float price, String images) {
		this.name = name;
		this.price = price;
		this.images = images;
	}

	public Services(Integer id, String name, Float price, String images) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.images = images;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Price", precision = 24, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "Images")
	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
