package com.vesmax.model;
// Generated Jun 29, 2019 6:03:20 PM by Hibernate Tools 5.1.7.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name = "services", schema = "dbo", catalog = "Qlspa")
public class Services  {

	private Integer id;
	private String name;
	private Float price;
	private Integer customerServiceId;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Services() {
	}

	public Services(String name, Float price, Integer customerServiceId, Set<Orders> orderses) {
		this.name = name;
		this.price = price;
		this.customerServiceId = customerServiceId;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Price", precision = 24, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "customer_serviceId")
	public Integer getCustomerServiceId() {
		return this.customerServiceId;
	}

	public void setCustomerServiceId(Integer customerServiceId) {
		this.customerServiceId = customerServiceId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
