package com.vesmax.model;
// Generated Aug 3, 2019 10:57:36 AM by Hibernate Tools 5.1.7.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "dbo", catalog = "Qlspa")
public class Users  {

	private Integer id;
	private String email;
	private String passwords;
	private Integer roles;
	private String name;
	private Boolean gender;
	private String birthday;
	private String photo;
	private Boolean custormerStatus;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Users() {
	}

	public Users(String email, String passwords, Integer roles, String name, Boolean gender,
			String birthday, String photo, Boolean custormerStatus, Set<Orders> orderses) {
		this.email = email;
		this.passwords = passwords;
		this.roles = roles;
		this.name = name;
		this.gender = gender;
		this.birthday = birthday;
		this.photo = photo;
		this.custormerStatus = custormerStatus;
		this.orderses = orderses;
	}
	
	public Users(String email, String passwords, String name, Integer roles,Boolean custormerStatus) {
		this.email = email;
		this.passwords = passwords;
		this.name = name;
		this.roles = roles;
		this.custormerStatus = custormerStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Passwords")
	public String getPasswords() {
		return this.passwords;
	}

	public void setPasswords(String passwords) {
		this.passwords = passwords;
	}

	@Column(name = "roles")
	public Integer getRoles() {
		return this.roles;
	}

	public void setRoles(Integer roles) {
		this.roles = roles;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Gender")
	public Boolean getGender() {
		return this.gender;
	}

	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	@Column(name = "Birthday", length = 1)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Column(name = "Photo")
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "custormer_status")
	public Boolean getCustormerStatus() {
		return this.custormerStatus;
	}

	public void setCustormerStatus(Boolean custormerStatus) {
		this.custormerStatus = custormerStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
